function export_fibres_to_csv(fibres, pixel_size_um, filename)
%Znaczenie poszczególnych pól:
% 1-7: dane wynikowe: nr_wlokna X Y Xunaligned Yunaligned R Warstwa
% 8-13: backlight: X Y Xunaligned Yunaligned R Luminancja
% 14-19: frontlight: X Y Xunaligned Yunaligned R Luminancja
% 20-25: bothlight: X Y Xunaligned Yunaligned R Luminancja
% 26-31: nolight: X Y Xunaligned Yunaligned R Luminancja

file = fopen(filename,'w');

for i=1:length(fibres)
    dataset = fibres(i);  
    data = [i, ...
            pixel_size_um*dataset.x, ...
            pixel_size_um*dataset.y, ...
            pixel_size_um*dataset.x_unaligned, ...
            pixel_size_um*dataset.y_unaligned, ...
            pixel_size_um*dataset.r, ...
            dataset.layer];

    if ~isfield(fibres, 'backlight')  
        data = [data NaN NaN NaN NaN];
    elseif (isempty(fibres(i).backlight))
        data = [data NaN NaN NaN NaN];
    else   
        dataset = fibres(i).backlight;
        data = [data, ...
                pixel_size_um*dataset.x, ...
                pixel_size_um*dataset.y, ...
                pixel_size_um*dataset.x_unaligned, ...
                pixel_size_um*dataset.y_unaligned, ...
                pixel_size_um*dataset.r, ...
                dataset.luminance];
    end;

    if ~isfield(fibres, 'frontlight')  
        data = [data NaN NaN NaN NaN];
    elseif (isempty(fibres(i).frontlight))
        data = [data NaN NaN NaN NaN];
    else   
        dataset = fibres(i).frontlight;
        data = [data, ...
                pixel_size_um*dataset.x, ...
                pixel_size_um*dataset.y, ...
                pixel_size_um*dataset.x_unaligned, ...
                pixel_size_um*dataset.y_unaligned, ...
                pixel_size_um*dataset.r, ...
                dataset.luminance];
    end;

    if ~isfield(fibres, 'bothlight')  
        data = [data NaN NaN NaN NaN];
    elseif (isempty(fibres(i).bothlight))
        data = [data NaN NaN NaN NaN];
    else   
        dataset = fibres(i).bothlight;
        data = [data, ...
                pixel_size_um*dataset.x, ...
                pixel_size_um*dataset.y, ...
                pixel_size_um*dataset.x_unaligned, ...
                pixel_size_um*dataset.y_unaligned, ...
                pixel_size_um*dataset.r, ...
                dataset.luminance];
    end;
    
    if ~isfield(fibres, 'nolight')  
        data = [data NaN NaN NaN NaN];
    elseif (isempty(fibres(i).nolight))
        data = [data NaN NaN NaN NaN];
    else   
        dataset = fibres(i).nolight;
        data = [data, ...
                pixel_size_um*dataset.x, ...
                pixel_size_um*dataset.y, ...
                pixel_size_um*dataset.x_unaligned, ...
                pixel_size_um*dataset.y_unaligned, ...
                pixel_size_um*dataset.r, ...
                dataset.luminance];
    end;
    
    fprintf(file,'%f\t',data);
    fprintf(file,'\r\n');                
end;

fclose(file);
