function export_errors_to_csv(fibres, filename)
%Pakuje dane o b��dach do pliku .csv. Wywo�a� PO mat_QA_2.

file = fopen(filename,'w');

for i=1:length(fibres)
    data = [i, ...
            fibres(i).errors.error_count, ...
            fibres(i).errors.wrong_neighbors_count, ...
            fibres(i).errors.backlight_not_detected, ...
            fibres(i).errors.frontlight_not_detected, ...
            fibres(i).errors.bothlight_not_detected, ...
            fibres(i).errors.backlight_low_light, ...
            fibres(i).errors.bothlight_low_light, ...
            fibres(i).errors.diameter_too_low, ...
            fibres(i).errors.diameter_too_high, ...
            fibres(i).errors.neighbor_distance_too_low, ...
            fibres(i).errors.neighbor_distance_too_high, ...
            fibres(i).errors.neighbor_angle_wrong, ...
            fibres(i).errors.out_of_bounds1, ...
            fibres(i).errors.out_of_bounds2, ...
            fibres(i).errors.outlying_area1, ...
            fibres(i).errors.outlying_area2];
    fprintf(file,'%d\t',data);
    fprintf(file,'\r\n');                
end;

fclose(file);
